{"Id":"0c2f6023-30e0-4c21-ac9e-0cd9b2c66f4c","Steps":[{"Name":"Change Text","Date":"2015-11-20T23:51:59.4702912+01:00","Commands":[{"CommandType":"Hercules.Model.ChangeTextCommand, Hercules.Model, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","Properties":{"Text":"Test","NodeId":"0c2f6023-30e0-4c21-ac9e-0cd9b2c66f4c"}}]}]}