{
  "id": "592a01f3-9546-4a3e-9dd7-b78f2a85ec96",
  "steps": [
    {
      "name": "Toggle",
      "date": "2015-11-21T00:27:21.7804408+01:00",
      "commands": [
        {
          "commandType": "ToggleCollapse",
          "properties": {
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Toggle",
      "date": "2015-11-21T00:27:21.1564744+01:00",
      "commands": [
        {
          "commandType": "ToggleCollapse",
          "properties": {
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Toggle",
      "date": "2015-11-21T00:27:20.5085392+01:00",
      "commands": [
        {
          "commandType": "ToggleCollapse",
          "properties": {
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Toggle",
      "date": "2015-11-21T00:27:19.8371489+01:00",
      "commands": [
        {
          "commandType": "ToggleCollapse",
          "properties": {
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Show Border",
      "date": "2015-11-21T00:27:17.9832388+01:00",
      "commands": [
        {
          "commandType": "ToggleHull",
          "properties": {
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Edit Icon",
      "date": "2015-11-21T00:27:10.629239+01:00",
      "commands": [
        {
          "commandType": "ChangeIcon",
          "properties": {
            "Key": "/Assets/Icons/User_Blue.png",
            "NodeId": "d52f0518-ed31-46e7-9141-eb7412428200"
          }
        }
      ]
    },
    {
      "name": "Edit Icon",
      "date": "2015-11-21T00:27:07.5034093+01:00",
      "commands": [
        {
          "commandType": "ChangeIcon",
          "properties": {
            "Key": "/Assets/Icons/Status_Flag_Green.png",
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Edit Color",
      "date": "2015-11-21T00:26:57.957388+01:00",
      "commands": [
        {
          "commandType": "ChangeColor",
          "properties": {
            "Index": 21,
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Edit Color",
      "date": "2015-11-21T00:26:54.9910522+01:00",
      "commands": [
        {
          "commandType": "ChangeColor",
          "properties": {
            "Index": 9,
            "NodeId": "d52f0518-ed31-46e7-9141-eb7412428200"
          }
        }
      ]
    },
    {
      "name": "Edit Color",
      "date": "2015-11-21T00:26:52.2383563+01:00",
      "commands": [
        {
          "commandType": "ChangeColor",
          "properties": {
            "Index": 17,
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:42.5440773+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "L_A2",
            "NodeId": "323cdaed-3c90-49a1-adc0-fa9a6fc3090d"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:38.7039765+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "L_A1",
            "NodeId": "3e6eb488-ee0a-482e-a6cb-4aa1812c8f8e"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:33.6320798+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "L_A",
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:29.0777865+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "R_B2",
            "NodeId": "5617e8fd-48f7-4423-aafb-afaeeaa297bc"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:26.6784378+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "R_B1",
            "NodeId": "7140a484-17f1-43f9-86a6-aa47f2379b5a"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:22.8229865+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "R_A2",
            "NodeId": "c3f17cc8-e834-43c4-8992-1b680a21438b"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:20.2639648+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "R_A1",
            "NodeId": "8ba99adc-5916-4927-a3f3-4e66fc4032b1"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:16.3896028+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "R_A",
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:13.5771929+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "R_B",
            "NodeId": "d52f0518-ed31-46e7-9141-eb7412428200"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:26:09.8480426+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "RA",
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Add Sibling",
      "date": "2015-11-21T00:25:58.9189007+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 1,
            "ChildId": "323cdaed-3c90-49a1-adc0-fa9a6fc3090d",
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Add Child",
      "date": "2015-11-21T00:25:58.6785033+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 0,
            "ChildId": "3e6eb488-ee0a-482e-a6cb-4aa1812c8f8e",
            "NodeId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e"
          }
        }
      ]
    },
    {
      "name": "Add Child",
      "date": "2015-11-21T00:25:57.80604+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 0,
            "ChildId": "2f7a6050-e84b-417f-b708-7f8a9b20a64e",
            "NodeId": "592a01f3-9546-4a3e-9dd7-b78f2a85ec96"
          }
        }
      ]
    },
    {
      "name": "Add Sibling",
      "date": "2015-11-21T00:25:56.2871849+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 2,
            "ChildId": "c3f17cc8-e834-43c4-8992-1b680a21438b",
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Add Child",
      "date": "2015-11-21T00:25:56.0063435+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 0,
            "ChildId": "8ba99adc-5916-4927-a3f3-4e66fc4032b1",
            "NodeId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352"
          }
        }
      ]
    },
    {
      "name": "Add Sibling",
      "date": "2015-11-21T00:25:54.4143638+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 2,
            "ChildId": "5617e8fd-48f7-4423-aafb-afaeeaa297bc",
            "NodeId": "d52f0518-ed31-46e7-9141-eb7412428200"
          }
        }
      ]
    },
    {
      "name": "Add Child",
      "date": "2015-11-21T00:25:54.1102883+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 0,
            "ChildId": "7140a484-17f1-43f9-86a6-aa47f2379b5a",
            "NodeId": "d52f0518-ed31-46e7-9141-eb7412428200"
          }
        }
      ]
    },
    {
      "name": "Add Sibling",
      "date": "2015-11-21T00:25:53.6949477+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 2,
            "ChildId": "d52f0518-ed31-46e7-9141-eb7412428200",
            "NodeId": "592a01f3-9546-4a3e-9dd7-b78f2a85ec96"
          }
        }
      ]
    },
    {
      "name": "Add Child",
      "date": "2015-11-21T00:25:52.5585702+01:00",
      "commands": [
        {
          "commandType": "InsertChild",
          "properties": {
            "key": null,
            "NodeSide": 0,
            "ChildId": "b3ac5b3d-74fd-4463-a6fd-d8205f9a4352",
            "NodeId": "592a01f3-9546-4a3e-9dd7-b78f2a85ec96"
          }
        }
      ]
    },
    {
      "name": "Change Text",
      "date": "2015-11-21T00:24:13.0515161+01:00",
      "commands": [
        {
          "commandType": "ChangeText",
          "properties": {
            "Text": "Test",
            "NodeId": "592a01f3-9546-4a3e-9dd7-b78f2a85ec96"
          }
        }
      ]
    }
  ]
}